- name: Install nginx
  ansible.builtin.yum:
    name: httpd
    state: installed
    
- name: Remove OLD Content
  ansible.builtin.file:
    path: /usr/share/nginx/html/* 
    state: absent
    
    
- name: Create Application Directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory    

- name: Download and Extract Frontend Content
  ansible.builtin.unarchive:
    src:  https://roboshop-artifacts.s3.amazonaws.com/frontend.zip 
    dest: /usr/share/nginx/html
    remote_src: yes
    

- name: Create RoboShop Config in Nginx
  ansible.builtin.copy:
    src: robo.txt
    dest: /etc/nginx/robo.txt

- name: Start Nginx Service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes
    
    
    