- name: Download Prometheus Node Exporter
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v1.5.0/node_exporter-1.5.0.linux-amd64.tar.gz
    dest: /opt
    remote_src: true

- name: Copy SystemD exporter
  ansible.builtin.template:
    src: exporter.service
    dest: /etc/systemd/system/node_exporter.service

- name: Start Exporter Service
  ansible.builtin.systemd:
    name: node_exporter
    state: restarted
    enabled: yes
    daemon-reload: yes